CreateConVar( "ammo_50AE_max", 		"35", 	FCVAR_REPLICATED )
CreateConVar( "ammo_762mm_max", 	"90",	FCVAR_REPLICATED )
CreateConVar( "ammo_556mm_max", 	"90", 	FCVAR_REPLICATED )
CreateConVar( "ammo_556mm_box_max", "200", 	FCVAR_REPLICATED )
CreateConVar( "ammo_338mag_max", 	"30", 	FCVAR_REPLICATED )
CreateConVar( "ammo_9mm_max", 		"120", 	FCVAR_REPLICATED )
CreateConVar( "ammo_buckshot_max", 	"32", 	FCVAR_REPLICATED )
CreateConVar( "ammo_45acp_max", 	"100", 	FCVAR_REPLICATED )
CreateConVar( "ammo_357sig_max", 	"52", 	FCVAR_REPLICATED )
CreateConVar( "ammo_57mm_max", 		"100", 	FCVAR_REPLICATED )

game.AddAmmoType( { name = "BULLET_PLAYER_50AE", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_50AE_max",		force = 2400, flags = 0, minsplash = 10, maxsplash = 14 } )
game.AddAmmoType( { name = "BULLET_PLAYER_762MM", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_762mm_max",	force = 2400, flags = 0, minsplash = 10, maxsplash = 14 } )
game.AddAmmoType( { name = "BULLET_PLAYER_556MM", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_556mm_max",	force = 2400, flags = 0, minsplash = 10, maxsplash = 14 } )
game.AddAmmoType( { name = "BULLET_PLAYER_556MM_BOX",	dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_556mm_box_max",force = 2400, flags = 0, minsplash = 10, maxsplash = 14 } )
game.AddAmmoType( { name = "BULLET_PLAYER_338MAG",		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_338mag_max",	force = 2800, flags = 0, minsplash = 12, maxsplash = 16 } )
game.AddAmmoType( { name = "BULLET_PLAYER_9MM", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_9mm_max", 		force = 2000, flags = 0, minsplash = 5,  maxsplash = 10 } )
game.AddAmmoType( { name = "BULLET_PLAYER_BUCKSHOT", 	dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_buckshot_max",	force = 600,  flags = 0, minsplash = 3,  maxsplash = 6  } )
game.AddAmmoType( { name = "BULLET_PLAYER_45ACP", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_45acp_max",	force = 2100, flags = 0, minsplash = 6,  maxsplash = 10 } )
game.AddAmmoType( { name = "BULLET_PLAYER_357SIG", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_357sig_max",	force = 2000, flags = 0, minsplash = 4,  maxsplash = 8  } )
game.AddAmmoType( { name = "BULLET_PLAYER_57MM", 		dmgtype = DMG_BULLET, tracer = TRACER_LINE, plydmg = 0, npcdmg = 0, maxcarry = "ammo_57mm_max",		force = 2000, flags = 0, minsplash = 4,  maxsplash = 8  } )